### PR TITLE
updated for 1.1.0 stack

### PR DESCRIPTION
**Pull request by mvandervliet**

### CODE REVIEW

**Comment by peterj** [comment]
@mvandervliet was this supposed to be merged?

**Comment by mvandervliet** [comment]
> @mvandervliet was this supposed to be merged?

No not yet

**Comment by junior** [comment]
> @mvandervliet was this supposed to be merged?

That's the "old" PR that was closed, and now re-opened, never merged.

**Comment by mvandervliet** [comment]
> > @mvandervliet was this supposed to be merged?
> 
> That's the "old" PR that was closed, and now re-opened, never merged.

Correct. Now the release is ready, so reopened

**Pull request merged**
