### PR TITLE
Update with SODA on Maven

### PR DESCRIPTION
**Pull request by gvenzl**
**Please do not pull yet!**
This is for the upcoming SODA release on Maven Central.

Signed-off-by: Gerald Venzl <gerald.venzl@oracle.com>

### CODE REVIEW

**Comment by jjspiegel** [comment]
LGTM

**Comment by gvenzl** [comment]
Once we have SODA on Maven, I will let you know!

**Comment by junior** [comment]
Changing to WIP to not get stale if takes longer the publishing

**Comment by jjspiegel** [comment]
@gvenzl @junior  - looks like it is there now: https://repo1.maven.org/maven2/com/oracle/database/soda/orajsoda/

**Comment by junior** [comment]
@jjspiegel @gvenzl Please update the [VERSION](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/src/carts/VERSION) file with a new patch version. (e.g.: 1.5.1) To allow the ci to create a new image.= with that change.

**Comment by gvenzl** [comment]
Yeah, also the Maven Search server has it synced now: https://search.maven.org/search?q=com.oracle.database.soda

Update to the version coming in a second!

**Comment by gvenzl** [comment]
And done, this should be all good now!

**Comment by junior** [comment]
Awesome to get from maven now.

**Pull request merged**
